### ISSUE TITLE
Make usage in the browser easier

### ISSUE THREAD

**Issue by realityking** [elgs/dns-zonefile#7]
I've started using this in a browser environment and it works great, but the handling of the template is a bit akward.

Would you be fine with converting this to ES6? This way the new template strings could be used and the dependency on `file` and `fs` could be removed. It would work as is with io.js, but require transpiling for node.js.

I'll put the work in, but I wanted to check before doing such an intrusive change.

**Comment by elgs** [comment]
@realityking, thanks for the idea that dependencies on `file` and `fs` should be removed. From the core library, instead of reading in the template from a file, it is better to read it from a string, so that the core library is friendly to the browsers, too. So, I totally agreed with your idea about removing the dependencies on `fs`. I will consider to make this change. If you have done that, pull request is appreciated, too.

As to ES6, I am sorry I don't have much insights into ES6, yet, though I understand ES6 is the future of Javascript. My suggestion would be to leave what currently works working, and start a new sibling with ES6.

**Comment by elgs** [comment]
@realityking I have removed the dependencies on `fs`and `path`, and added `bower` support. Hopefully it is browser friendly now. :)

**Comment by realityking** [comment]
Sorry I didn't get back to this earlier. I just replaced my modified version with the bower dependency and it works like a charm! Thank you.

One minor nitpick: bower is a bit sensitive to git tags, it would be great if you could tag versions.

**Comment by elgs** [comment]
Hi @realityking it's great it works for you. I just made a tag. Thanks for reminding me about the tag.

Also, I don't feel comfortable to bind the generate and parse function on the `window`, in order to avoid conflict, I changed the name as `zonefile_generate` and `zonefile_parse`. However, I still think it looks ugly. Do you mind if I create a class function and put the generate and parse function in its own class. The consequence will be that you have to modify your code and initialize a new object yourself in order to use generate and parse. How do you think?

**Comment by realityking** [comment]
@elgs I don't mind code changes, especially for small and isolated libraries.

I guess you mean it should look like this (ignoring the parser for a moment)?

```javascript
var options = {};
var serializer = new ZoneFileSerializer;
var zoneFile = serializer.serialize(options);
```

Different but related point: Since the parser and the serializer are completely separate code wise, IMHO, it would be cleaner to have two modules. Would you be fine with a pull request to do that?

**Comment by elgs** [comment]
Yes, that's basically what I meant. And I agreed leaving parser and generator (serializer) in separate modules would be cleaner. And sure, pull requests will be appreciated. :) Thanks @realityking
